### ISSUE TITLE
HUD Animations: Invalid float parsing in some cultures

### ISSUE THREAD

**Issue by chara22322** [cooolbros/hud-merger#5] opened 2024-02-12 22:52 UTC
I got this error when i was merging this: tf2huds.dev/hud/MonoHud with this: tf2huds.dev/hud/DarHUD. If i knew where the default location of the certain file i am merging is, then i can search for it more easily
![image](https://github.com/cooolbros/hud-merger/assets/97923700/91f63106-7cfe-4f79-b237-0925aa90bb88)

**Comment by cooolbros** [comment] 2024-02-13 02:23
Thanks for reporting this issue, usually the file that the error occurred in is displayed in the message, but this error actually looks to be a bug in the hud merger itself.

So far I havent been able to reproduce this error myself, because after searching online it seems to be an issue with the number parsing in dotnet itself, but only in certain languages. 

Can you tell me what language your windows OS is set to so (for example US english or UK english) I can try to reproduce this error?

**Comment by cooolbros** [comment] 2024-02-13 02:43
Update: I found that the french language (`fr`) parses decimals that resemble `0,8` as 0.8 and fails for decimals used in HUD animations such as `0.8`, which matches the behaviour in the initial report

**Comment by cooolbros** [comment] 2024-04-19 14:15
Fixed in 2.0.1

**Closed as completed by cooolbros** 2024-04-19 14:15 UTC
